server:
    port: 8085
spring:
    application:
        name: resthomecontrollerribbon
configuracionusuarios:
   ribbon:
       DeploymentContextBasedVipAddresses: configuracionusuarios
       NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
crearnotificacion:
   ribbon:
       DeploymentContextBasedVipAddresses: crearnotificacion
       NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList